### ISSUE TITLE
php5-curl issues

### ISSUE THREAD

**Issue by chomu712** [googleinurl/SCANNER-INURLBR#3] opened 2016-04-15 13:38 UTC
i installed in kali 2016. i have this error [ INFO ] INSTALLING THE LIBRARY php5-curl ex: php5-curl apt-get install
but i have installed it already

apt-get install php5-curl
Reading package lists… Done
Building dependency tree
Reading state information… Done
php5-curl is already the newest version (5.6.19+dfsg-2+b1).

i also have xampp installed
 Please i need help to solve this issue

**Comment by pandabr** [comment] 2016-08-30 14:37
me idem.. help?

**Comment by weslley75** [comment] 2016-08-30 14:39
apt-get install php-curl

**Comment by arbazhussain149** [comment] 2017-03-12 12:00
Kali Linux 2.0

[ INFO ] INSTALLING THE LIBRARY php5-curl ex: php5-curl apt-get install

# apt-get install php5-curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-curl' has no installation candidate

**Comment by amiralkizaru** [comment] 2017-10-02 10:55
Guys i found the solution the problem is due to the php 7.0 version we need to downgrade to php 5.6
follow instructions in this link : https://www.tecmint.com/install-different-php-versions-in-ubuntu/
Stay in Peace
It Worked for me

**Comment by legoldenbeets** [comment] 2018-08-21 16:29
easy way >> sudo apt-get install php-gd php-mysql

**Comment by amiralkizaru** [comment] 2018-12-23 13:41
Hello
Im running

> DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.1"
VERSION_ID="2019.1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

And when I install php5 curl , Metasploit and some other tool are removed automatically ...
I want know how to avoid that

> root@kali:~# apt install metasploit-framework
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apache2-data apache2-utils cython libadns1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libbind9-160 libboost-atomic1.62.0 libboost-chrono1.62.0 libboost-date-time1.62.0
  libboost-filesystem1.62.0 libboost-program-options1.62.0 libboost-serialization1.62.0 libboost-test1.62.0 libboost-timer1.62.0 libdate-manip-perl libdns1102 libenca0
  libirs160 libisc169 libisccc160 libisccfg160 libluajit-5.1-2 libluajit-5.1-common liblwres160 libperl5.26 libpoppler74 libprotobuf-lite10 libprotobuf10
  libqgis-analysis2.18.24 libqgis-core2.18.24 libqgis-gui2.18.24 libqgis-networkanalysis2.18.24 libqgis-server2.18.24 libqgispython2.18.24 libradare2-2.9 libsane-extras
  libsane-extras-common libssl1.0.0 libunbound2 multiarch-support nginx openjdk-10-jdk openjdk-10-jdk-headless openjdk-10-jre osslsigncode php7.3-common python-adns
  python-alembic python-anyjson python-autobahn python-babel python-babel-localedata python-backports.ssl-match-hostname python-capstone python-cbor
  python-configargparse python-construct python-couchdbkit python-deprecation python-easygui python-editor python-feedparser python-filedepot python-filteralchemy
  python-flask-babelex python-flask-classful python-flask-login python-flask-mail python-flask-principal python-flask-security python-flask-session
  python-flask-sqlalchemy python-flaskext.wtf python-h2 python-hpack python-html2text python-http-parser python-hyperframe python-ipy python-jwt python-levenshtein
  python-libemu python-lz4 python-marshmallow python-marshmallow-sqlalchemy python-metaconfig python-mockito python-msgpack python-nplusone python-packaging
  python-passlib python-pefile python-pexpect python-ptyprocess python-pydot python-pyperclip python-qrcode python-restkit python-selenium python-slugify python-snappy
  python-socketpool python-speaklater python-sqlalchemy-schemadisplay python-tqdm python-trie python-trollius python-txaio python-u-msgpack python-ubjson
  python-unidecode python-urwid python-webargs python-websocket python-whoosh python-wsaccel python-wtforms ruby-ffi ruby-opt-parse-validator ruby-progressbar ruby-yajl
  u3-tool x11proto-dri2-dev x11proto-gl-dev zsh zsh-common
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  curl libcurl4
Suggested packages:
  clamav clamav-daemon
The following packages will be REMOVED:
  libcurl3 php5.6-curl
The following NEW packages will be installed:
  curl libcurl4 metasploit-framework

**Comment by alexandrepessoa33** [comment] 2021-04-06 14:19
Write the command: sudo apt-get install php-curl
Worked for me. I found it in https://installlion.com/kali/kali/main/p/php-curl/install/index.html

**Comment by MrCl0wnLab** [comment] 2024-09-13 02:23
## Fixed

- https://github.com/MrCl0wnLab/SCANNER-INURLBR (new repo)

**Closed** 2024-09-13 02:28 UTC
